### ISSUE TITLE
[feat] Allow to configure window options for the hovers, such as borders

### ISSUE THREAD

**Issue by lervag** [kndndrj/nvim-dbee#102]
The hover options are set here:

https://github.com/kndndrj/nvim-dbee/blob/8e557d8fb2aee41769104f1ceef1a69aac733ce1/lua/dbee/ui/common/floats.lua#L253-L263

I would very much want to pass some config here to have the hovers consistent with my personal config. E.g., I want to adjust the borders and possibly the title.

**Comment by petobens** [comment]
Hi @kndndrj. I tried your latest PR that should close this issue. One thing I noticed is that if I add something like:
```lua
        window_options = {
            number = true,
            relativenumber = true,
        },
```
then the first time I run `dbee.toggle()` line numbers are shown but if I toggle db again then the line numbers disappear. Can the window option settings be made persistent? (i.e survive toggling)? Thanks!

**Comment by kndndrj** [comment]
Hey @petobens thanks for testing, I'll look into it.

**Comment by kndndrj** [comment]
@petobens btw, which UI element is in question? Or is it all of them?

**Comment by kndndrj** [comment]
@petobens should be fixed now

**Comment by petobens** [comment]
Thanks!

**Comment by lervag** [comment]
Thanks for this, I'll be testing it now - sorry for not being in time to test before the merge!

**Comment by lervag** [comment]
This seems to work very well, thanks! However, I found a case where the custom float options were not passed - probably best explained with a simple screenshot:

![image](https://github.com/kndndrj/nvim-dbee/assets/998898/572735df-7d44-4ea4-9755-a3e1b027172e)

I.e.: The hover for database picker.

**Comment by lervag** [comment]
And also for the "Select a query" menu.
