### ISSUE TITLE
Hide some schemas from drawer view

### ISSUE THREAD

**Issue by petobens** [kndndrj/nvim-dbee#103]
Is it possible already (or add a feature) to hide some schemas from the drawer view? For instance in postgres I would like to hide the `information_schema` and the `pg_catalog`. Thanks in advance

**Comment by kndndrj** [comment]
Hey @petobens this is currently not possible and honestly, I don't like the idea too much.

I'm closing this, because I think this feature would be too big of a maintanence burden for too little return. Sorry.

**Comment by petobens** [comment]
Ok. I migrating from dadbod/dbui that has this functionality as per: https://github.com/kristijanhusak/vim-dadbod-ui/blob/066922699bdf1c6e14d517b844454b12b93ce25a/autoload/db_ui/drawer.vim#L717

But if it's too cumbersone to implement /mantain I can understand that.
