### ISSUE TITLE
Simple Question: How to Disable Automatic Minimization of Query Output in MySQL?

### ISSUE THREAD

**Issue by Mike-18awq** [kndndrj/nvim-dbee#122]
Actual Behavior:
![Screenshot_460](https://github.com/kndndrj/nvim-dbee/assets/137745753/130d39d2-ec9c-430a-89c1-e07f2f2a0450)

Expected Behavior:
![Screenshot_461](https://github.com/kndndrj/nvim-dbee/assets/137745753/0c38b0bc-2753-437c-bccb-a9fbda4ebdae)

**Comment by kndndrj** [comment]
is this dadbod? please ask at dadbod (or dadbod-ui) repos.

If I'm really mistaken, please reopen the issue, thanks.
