### ISSUE TITLE
MySQL DSN with a port

### ISSUE THREAD

**Issue by weirdan** [kndndrj/nvim-dbee#32]
I'm trying to connect to a MySQL server available on localhost on non-standard port.

I've tried the following DSNs (all fail):

* `user_name:pass_word@tcp(127.0.0.1:3308)/dbname`
  ```
  Error  05:20:44 PM notify.error nvim-dbee mysql: invalid url: parse "user_name:pass_word@tcp(127.0.0.1:3308)/dbname": first path segment in URL cannot contain colon
  Error  05:20:44 PM notify.error nvim-dbee [handler]: .../share/lazynvim/lazy/nvim-dbee/lua/dbee/handler/conn.lua:65: problem adding connection
  ```
* `mysql://user_name:pass_word@tcp(127.0.0.1:3308)/dbname`
  ```
  Error  05:23:29 PM notify.error nvim-dbee mysql: invalid url: parse "mysql://user_name:pass_word@tcp(127.0.0.1:3308)/dbname": invalid port ":3308)" after host
  Error  05:23:29 PM notify.error nvim-dbee [handler]: .../share/lazynvim/lazy/nvim-dbee/lua/dbee/handler/conn.lua:65: problem adding connection
  ```
* `mysql://user_name:pass_word@127.0.0.1/dbname`
  ```
  Error  05:24:30 PM notify.error nvim-dbee unable to connect to mysql database: default addr for network '127.0.0.1:3308' unknown
  Error  05:24:30 PM notify.error nvim-dbee [handler]: .../share/lazynvim/lazy/nvim-dbee/lua/dbee/handler/conn.lua:65: problem adding connection
  ```

This is similar to the #14, but the solution posted there no longer works due to URL parsing check added since it was posted: https://github.com/kndndrj/nvim-dbee/commit/d461eb19031ee2a88c896d372bd110c30f901b93

**Comment by kndndrj** [comment]
@weirdan Thanks for postinv the issue. I think simplified the url check in mysql driver in a recent PR. Apparently I missed a few cases.
I'll look into this issue as soon as I have some time, meanwhile you can check if an older commit works for you.

**Comment by weirdan** [comment]
For future reference, MySQL DSN, as implemented here, does not include 'protocol' prefix. A working example is `user_name:pass_word@tcp(127.0.0.1:3308)/database_name`.
