### ISSUE TITLE
Unable to connect to sqlite db `Dbee_register_connection`  'dbee' is not executable

### ISSUE THREAD

**Issue by kaykhan** [kndndrj/nvim-dbee#39]
Hi i am trying this plugin for the first time. Attempting to connect to a sqlite db in my current directory.

```
{
"kndndrj/nvim-dbee",
dependencies = {
	"MunifTanjim/nui.nvim",
},
build = function()
	-- Install tries to automatically detect the install method.
	-- if it fails, try calling it with one of these parameters:
	--    "curl", "wget", "bitsadmin", "go"
	require("dbee").install()
end,
config = function()
	require("dbee").setup({ lazy = true, debug = true })
end,
},
```
![image](https://github.com/kndndrj/nvim-dbee/assets/5202527/62f084fe-50c4-46bd-a188-049b7acc075c)

`:w`

![image](https://github.com/kndndrj/nvim-dbee/assets/5202527/da7134eb-4b17-47bf-bc96-8ae3cd4cca8b)

Despite enabling logs

```
cat ~/.cache/nvim/dbee/dbee.log                                                                                                                                                                            
cat: /home/kay/.cache/nvim/dbee/dbee.log: No such file or directory
```

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

Full error message:

>   Error  08:41:07 notify.error nvim-dbee [handler]: BufWriteCmd Autocommands for "<buffer=34>"..FuncUndefined Autocommands for "Dbee_register_connection"..function remote#define#FunctionBootstrap[1]..remote#host#Require[10]..<SNR>29_Start_dbee, line 1: Vim(return):E475: Invalid value for argument cmd: 'dbee' is not executable

**Comment by kndndrj** [comment]
Hey, I think the `install()` hasn't finished yet, so backend is not executable.
Can you try running `require"dbee".install()` and waiting for a while. The download is pretty big. If you don't want to download a precompiled binary, and have go toolchain installed, try running `require"dbee".install("cgo")` or (if that doesn`t work `install("go")

Let me know if that helped :)

**Comment by kaykhan** [comment]
> Hey, I think the `install()` hasn't finished yet, so backend is not executable. Can you try running `require"dbee".install()` and waiting for a while. The download is pretty big. If you don't want to download a precompiled binary, and have go toolchain installed, try running `require"dbee".install("cgo")` or (if that doesn`t work `install("go")
> 
> Let me know if that helped :)

Hi thanks for the response

> [dbee install]: installing dbee with:  wget chmod
> [dbee install]: running command: wget
> [dbee install]: running command: chmod
> [dbee install]: successfully installed

after that it worked
