### ISSUE TITLE
Strange characters in place of symbols

### ISSUE THREAD

**Issue by jaswdr** [kndndrj/nvim-dbee#47]
This is my first time using the plugin, I find it really useful, although in my current setup (Ubuntu 22.04) for some reason some symbols are wrongly being showed (see below screenshot). Do you know what could cause this kind of issue? This is probably something related to my current font  ("Source Code Pro"), can you tell me which fonts are compatible with the symbols used in the project?

![image](https://github.com/kndndrj/nvim-dbee/assets/6409113/e8d17ced-c320-4c0a-b267-b4535c911b4c)

**Comment by kndndrj** [comment]
@jaswdr as you figured out yourself, this is an issue with fonts.

Be sure to use a patched nerd font. If you dont know what nerd fonts are, they are basically normal fonts, patched with a bunch of icons. You can find a lot of pre-patched fonts on their website, but if you don't find your font up there, they have a tool on their github page with instructions to patch your own.

Also note that you should use nerd fonts version 3.0 for dbee. Older versions could be missing some symbols that dbee relies on.

Hope this helps!

**Comment by jaswdr** [comment]
Thank you, I'll do that 👍
