### ISSUE TITLE
Specify ScratchPad directory for each connection

### ISSUE THREAD

**Issue by stephenafamo** [kndndrj/nvim-dbee#49]
The saved queries are likely unique for each connection, or at least for each project. Right now it seems the scratchpad directory is global and not customizable.

I am loading the connections for each project using ENVIRONMENT variables, I would also like to save queries for each connection in a unique folder.

**Comment by kndndrj** [comment]
Agree, having scratchpads local to connection would be nice.

**Comment by kndndrj** [comment]
@stephenafamo this has been addressed with local notes now, so I'm closing this issue.

If you feel the functionality is not good enough or you think something is missing, feel free to reopen it.

**Comment by stephenafamo** [comment]
Where can I find documentation about the local notes
