### ISSUE TITLE
dbee not found after add the plugin by lazy

### ISSUE THREAD

**Issue by LintaoAmons** [kndndrj/nvim-dbee#53]
I added this plugin by lazy, but when I trying to add a new connection, it says that `dbee not found`

I have to do find the install path and then manually give the runnable permission and add it to the PATH, then it can work

```
nvim/dbee/bin
❯ ls
dbee

nvim/dbee/bin
❯ dbee
zsh: command not found: dbee

nvim/dbee/bin
❯ ./dbee
zsh: permission denied: ./dbee

nvim/dbee/bin
❯ chmod u+x dbee

nvim/dbee/bin
❯ ./dbee
^C

nvim/dbee/bin took 5s
❯ export PATH=$(pwd):$PATH

nvim/dbee/bin
❯ cd

~
❯ dbee
^C
```

**Comment by kndndrj** [comment]
hi @LintaoAmons can you also provide the lazy entry and plugin's config? Thanks.

**Comment by kndndrj** [comment]
@LintaoAmons there isn't any dbee related config in the file 😅

**Comment by LintaoAmons** [comment]
Oh... Sorry I forgot I've removed it...
But I think I just copied the config in the README...

Since I found nobody else reporting this issue, I guess it must be some strange case, but it's fine, I shall try later
