### ISSUE TITLE
[Feature] Nvim Tree integration  

### ISSUE THREAD

**Issue by volga629-1** [kndndrj/nvim-dbee#54]
Hello Everyone, 
This is request to integrate with Nvim Tree, that connection tree  list will be open under same tree as Nvim Tree  for easy navigation.

**Comment by kndndrj** [comment]
Hi @volga629-1,

thanks for the suggestion, however I fail to see how this  is desirable. Even if it is, I think it's an integration which (imo) does not belong in dbee.

If we start supporting nvim-tree, we must also support nerdtree, neotree and netrw and probably even more.

I'm still prepared to hear any additional arguments in favor of this kind on integration though.

Thanks.

**Comment by volga629-1** [comment]
Then main argument is to integrate with most common one.  Just to have logical completion for the plugin ( seamless start ).

**Comment by kndndrj** [comment]
Sorry, but I think this doesn't belong in the "core" repo. This seems more like something an extension would do.

Closing because of that.
