### ISSUE TITLE
Can't see error output for failed queries?

### ISSUE THREAD

**Issue by willruggiano** [kndndrj/nvim-dbee#59]
I'm trying out the refactored version of dbee and everything is great! Except I can't figure out how to see the error output for failed queries :/

The result buffer just shows:
"Call execution failed after ..."

and the call log just says "state: executing_failed"

The old version of dbee used vim.notify (I think?) to display runtime errors?

**Comment by kndndrj** [comment]
Thanks for reporting (both issues) Looks like I need to check postgres and error passing a bit more. Thanks for reporting!
