### ISSUE TITLE
show column number on `relativenumber` options

### ISSUE THREAD

**Issue by hieulw** [kndndrj/nvim-dbee#74]
![image](https://github.com/kndndrj/nvim-dbee/assets/13571960/2a5fe4c8-8640-4d6e-bfe4-f58521f61c09)

Hello my options have `vim.opt.relativenumber = true`. How can I disable line number in dbee-drawer, dbee-call-log, dbee-result. They don't have custom buftype or filetype to customize by autocmd, they're just filename

**Comment by willruggiano** [comment]
Yeah, this is something that was lost in the refactor. The pre-refactor version had window_layout hooks that could be used for this exact purpose. Post-refactor, you have to implement an entire layout which isn't ideal if you're just trying to set some window options.

You _can_ create autocmds for the filenames, e.g.
```lua
vim.api.nvim_create_autocmd("WinNew", {
  pattern = "dbee-call-log",
  callback = function()
    -- do whatever you want in here, e.g.
    vim.wo.relativenumber = true
  end
})
```

however this doesn't always work. For example, when first opening the dbee ui these autocmds don't fire (or they do but get [overwritten](https://github.com/kndndrj/nvim-dbee/blob/master/lua/dbee/ui/drawer/init.lua#L323) [by](https://github.com/kndndrj/nvim-dbee/blob/master/lua/dbee/ui/result/init.lua#L419) [dbee](https://github.com/kndndrj/nvim-dbee/blob/master/lua/dbee/ui/call_log.lua#L274), not sure which, or why). They _do_ fire upon re-opening the dbee ui - at least in my setup. Specifically for dbee-result, this one never seems to hit for me.

Anyways, I too would like to be able to set a few options for each of these windows. Maybe we can convince @kndndrj to add the window_layout hooks back, or the window_commands, or something :stuck_out_tongue_winking_eye:

**Comment by kndndrj** [comment]
Window/buffer options sure would make sense.
