### ISSUE TITLE
unknown function: Dbee_register_connection

### ISSUE THREAD

**Issue by napisani** [kndndrj/nvim-dbee#8]
Hi there!

I'm really looking forward to trying out this plugin. Also, I'm really fascinated to read through your code and see how the go-lua interop works.

When I first attempted to setup a connection to my local db, I started getting this error on startup and all subsequent execution commands seemed to fail as well.

Here is a screenshot of the error
<img width="737" alt="Screenshot 2023-05-14 at 10 15 05 PM" src="https://github.com/kndndrj/nvim-dbee/assets/426949/e1927bc5-a9b3-4b16-807a-f683eb10f929">

Here is my configuration:

Packer:
```lua
  use ({
  "kndndrj/nvim-dbee",
  requires = {
    "MunifTanjim/nui.nvim",
  },
  build = function()
    -- Install tries to automatically detect the install method.
    -- if it fails, try calling it with one of these parameters:
    --    "curl", "wget", "bitsadmin", "go"
    require("dbee").install()
  end,
  run = function()
    -- Install tries to automatically detect the install method.
    -- if it fails, try calling it with one of these parameters:
    --    "curl", "wget", "bitsadmin", "go"
    require("dbee").install()
  end,
})

```
here is my config function called from my init.vim file:
```lua
local status_ok, dbee = pcall(require, "dbee")
if not status_ok then
	vim.notify("dbee not found ")
	return
end
dbee.setup({
 connections = {
    {
      name = "examplemysql",
      type = "mysql",
      url = "mysql://root:redacted@localhost:3306/db1",
    },
  }
})

```
Is there a mistake that I made in the config?
Thanks in advance,
~Nick

**Comment by kndndrj** [comment]
Hey @napisani, thanks for trying out the plugin.

I probably won't be able to check anything with my pc thia week, but nonetheless, lets try some things:
I see you aren't calling the setup function from packer (e.g. you aren't lazy loading the plugin) For some reason nvim has some trouble running go commands on startup. Try putting `lazy = true` in your config, so the setup looks like this:
```
dbee.setup({
  lazy = true,
 connections = {
    {
      name = "examplemysql",
      type = "mysql",
      url = "mysql://root:redacted@localhost:3306/db1",
    },
  }
})
```

Please let me know if it works!

**Comment by napisani** [comment]
Thank you, I think I'm one step closer now. 
Although now I'm running to this error after running the following command 

Cmd:
```
lua require("dbee").execute("select * from person")
```

Error:
```
connection with id examplemysqlmysql not registered
```

Sorry to be a pain, but I appreciate your help

**Comment by napisani** [comment]
I hope you didnt spent too much time racking your brain on this one. I was able to finally get it working by changing my connection string to this format:
```
dbee.setup({
	lazy = true,
	connections = {
		{
			name = "examplemysql",
			type = "mysql",
			url = "root:password@(localhost:3306)/db1",
		},
	},
})

```

Thanks again for your help!
