### ISSUE TITLE
DrawerUI is broken on windows

### ISSUE THREAD

**Issue by JustBarnt** [kndndrj/nvim-dbee#93]
The creation for the `DrawerUI` is broken. Creation of the node id is done by using `os.clock()` which on Windows returns the same exact timestamp of `nvim` formatted like `X.xxx` where as on unix it returns `X.xxxxxxx` on windows the timestamps are the exact same as Unix

Edit: Update. Did some [research](https://github.com/LuaJIT/LuaJIT/issues/442) appears that both are accurate but `clock` works differently based on what OS you are using. So using `os.clock()` to try to create a unqiue id for those `nui` nodes it not a good idea.

**Comment by JustBarnt** [comment]
Well the DrawUI was the only thing I noticed and after my PR the only other issue I seemed to have was it not being able to find my saved notes after I ended a session

**Comment by JustBarnt** [comment]
I mean at least for me. Once I forked and fixed the fixing of the GUID instead of using `os.clock` it worked for what I was using except for my notes being remembered. 

If you'd be interested you could let me know where some of those Unix hardcoded areas are and I could look into making the windows and Unix friendly!

**Comment by kndndrj** [comment]
Cool!
The related PR has been merged and all uses of os.clock have been changed to utils.random_string, so this should be sufficient.

If it still doesn't work for some reason, feel free to reopen this issue or create a new one.

Thanks!
